services:
  nginx:
    image: nginx:latest
    container_name: quint-felicity
    volumes:
      - ./public:/var/www/html/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/var/www/html/uploads:ro
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - webnet
      - phpnet

  php:
    image: ghcr.io/teaspoon-de/prod-php:latest
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./public:/var/www/html/public:ro
      - ./src:/var/www/html/src:ro
      - ./uploads:/var/www/html/uploads
    working_dir: /var/www/html
    networks:
      - phpnet
      - dbnet

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD_QUINT_FELICITY: ${DB_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./db-init/01-db-init.sql:/docker-entrypoint-initdb.d/quint-felicity-01.sql
      - ./db-init/02-create-user.sh:/docker-entrypoint-initdb.d/quint-felicity-02.sh
      - ./db-init/03-import-data.sql:/docker-entrypoint-initdb.d/quint-felicity-03.sql
    networks:
      - dbnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - dbnet

networks:
  webnet:
    external: false
  dbnet:
    external: false
  phpnet:
