services:
  nginx:
    image: nginx:latest
    container_name: member-quint-felicity
    environment:
      VIRTUAL_HOST: member.quint-felicity.de
      LETSENCRYPT_HOST: member.quint-felicity.de
      LETSENCRYPT_EMAIL: info@quint-felicity.de
    volumes:
      - ./public:/var/www/html/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../data/uploads:/var/www/html/uploads:ro
    depends_on:
      - php
    networks:
      - webnet
      - phpnet

  php:
    image: ghcr.io/teaspoon-de/prod-php:latest
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./public:/var/www/html/public:ro
      - ./src:/var/www/html/src:ro
      - ../data/uploads:/var/www/html/uploads:rw
    working_dir: /var/www/html
    networks:
      - phpnet
      - dbnet

networks:
  webnet:
    external: true
  dbnet:
    external: true
  phpnet:
